{
 "title": "Quizly User Analytics",
 "tags": [
  "app",
  "business"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Player Accuracy (Correct vs Incorrect)",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (quizly_answers_total)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total Games Started",
   "type": "stat",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(quizly_game_started_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Answers Over Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(status) (rate(quizly_answers_total[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Correct Answers by Player",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by(player) (quizly_answers_total{status=\"correct\"})",
     "legendFormat": "{{player}}"
    }
   ]
  }
 ]
}